<?php

namespace Database\Seeders;

use App\Models\Poblacion;
use App\Models\Provincia;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PoblacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipios = [
            'Álava' => ['Vitoria-Gasteiz', 'Amurrio', 'Llodio', 'Laudio', 'Samaniego', 'Armiñón', 'Villarreal de Álava', 'Ribera Baja', 'Samaniego'],
            'Albacete' => ['Albacete', 'Almansa', 'Hellín', 'La Rasa', 'Munera', 'Valdeganga', 'Chinchilla de Montearagón', 'La Gineta'],
            'Alicante' => [
                "Adsubia",
                "Agost",
                "Agres",
                "Aigües",
                "Albatera",
                "Alcalalí",
                "Alcocer de Planes",
                "Alcoleja",
                "Alcoy",
                "Alfafara",
                "Alfàs del Pi",
                "Algorfa",
                "Algueña",
                "Alicante",
                "Almoradí",
                "Almudaina",
                "Alqueria d'Asnar",
                "Altea",
                "Aspe",
                "Balones",
                "Banyeres de Mariola",
                "Benasau",
                "Beneixama",
                "Benejúzar",
                "Benferri",
                "Beniarbeig",
                "Beniardá",
                "Beniarrés",
                "Benidoleig",
                "Benidorm",
                "Benifallim",
                "Benifato",
                "Benigembla",
                "Benijófar",
                "Benilloba",
                "Benillup",
                "Benimantell",
                "Benimarfull",
                "Benimassot",
                "Benimeli",
                "Benissa",
                "Benitachell",
                "Biar",
                "Bigastro",
                "Bolulla",
                "Busot",
                "Callosa de Segura",
                "Callosa d'en Sarrià",
                "Calpe",
                "Campello",
                "Campo de Mirra",
                "Cañada",
                "Castalla",
                "Castell de Castells",
                "Catral",
                "Cocentaina",
                "Confrides",
                "Cox",
                "Crevillent",
                "Daya Nueva",
                "Daya Vieja",
                "Dénia",
                "Dolores",
                "Elche",
                "Elda",
                "Facheca",
                "Famorca",
                "Finestrat",
                "Formentera del Segura",
                "Gata de Gorgos",
                "Gaianes",
                "Gorga",
                "Granja de Rocamora",
                "Guardamar del Segura",
                "Hondón de las Nieves",
                "Hondón de los Frailes",
                "Ibi",
                "Jacarilla",
                "Jávea",
                "Jijona",
                "Llíber",
                "Lorcha",
                "Millena",
                "Monforte del Cid",
                "Monóvar",
                "Montesinos",
                "Murla",
                "Muro de Alcoy",
                "Mutxamel",
                "Novelda",
                "Nucia",
                "Ondara",
                "Onil",
                "Orba",
                "Orihuela",
                "Parcent",
                "Pedreguer",
                "Pego",
                "Penàguila",
                "Petrer",
                "Pilar de la Horadada",
                "Pinós",
                "Planes",
                "Polop",
                "Rafal",
                "Ràfol d'Almúnia",
                "Redován",
                "Relleu",
                "Rojales",
                "Sagra",
                "Salinas",
                "San Fulgencio",
                "San Isidro",
                "San Miguel de Salinas",
                "San Vicente del Raspeig",
                "Sanet y Negrals",
                "Sant Joan d'Alacant",
                "Santa Pola",
                "Sax",
                "Sella",
                "Senija",
                "Tàrbena",
                "Teulada",
                "Tibi",
                "Tollos",
                "Tormos",
                "Torremanzanas",
                "Torrevieja",
                "Vall de Alcalà",
                "Vall de Ebo",
                "Vall de Gallinera",
                "Vall de Laguar",
                "Verger",
                "Villajoyosa",
                "Villena"
            ],
            'Almería' => ['Almería', 'El Ejido', 'Roquetas de Mar', 'Níjar', 'Vícar', 'Huércal de Almería', 'Adra', 'Albox', 'Berja'],
            'Ávila' => ['Ávila', 'Arévalo', 'El Tiemblo', 'Cebreros', 'Mijares', 'San Esteban del Valle', 'Sotillo de la Adrada', 'Navaluenga'],
            'Badajoz' => ['Badajoz', 'Mérida', 'Don Benito', 'Villanueva de la Serena', 'Olivenza', 'Zafra', 'Villafranca de los Barros', 'Almendralejo'],
            'Barcelona' => ['Barcelona', 'Badalona', 'Hospitalet de Llobregat', 'Terrassa', 'Sabadell', 'Mataró', 'Cornellá de Llobregat', 'Sant Cugat del Vallès'],
            'Burgos' => ['Burgos', 'Aranda de Duero', 'Miranda de Ebro', 'Briviesca', 'Belorado', 'Villarcayo', 'Valle de Mena', 'Espinosa de los Monteros'],
            'Cáceres' => ['Cáceres', 'Plasencia', 'Badajoz', 'Don Benito', 'Villanueva de la Serena', 'Olivenza', 'Zafra', 'Villafranca de los Barros'],
            'Cádiz' => ['Cádiz', 'Algeciras', 'Jerez de la Frontera', 'San Fernando', 'La Línea de la Concepción', 'Sanlúcar de Barrameda', 'Chiclana de la Frontera'],
            'Cantabria' => ['Santander', 'Torrelavega', 'Camargo', 'Astillero', 'Castro Urdiales', 'Laredo', 'Colindres', 'Suances'],
            'Castellón' => ['Castellón de la Plana', 'Vila-real', 'Benicarló', 'Burriana', 'Oropesa del Mar', 'Almazora', 'Nules', 'Vinaroz'],
            'Ciudad Real' => ['Ciudad Real', 'Alcázar de San Juan', 'Puertollano', 'Valdepeñas', 'Manzanares', 'Tomelloso', 'Campo de Criptana'],
            'Córdoba' => ['Córdoba', 'Lucena', 'Montilla', 'Puente Genil', 'Baena', 'Priego de Córdoba', 'Pozoblanco', 'Peñarroya-Pueblonuevo'],
            'Cuenca' => ['Cuenca', 'Tarancón', 'San Clemente', 'Mota del Cuervo', 'Villanueva de la Jara', 'Iniesta', 'Cañete', 'Mira'],
            'Gerona' => ['Gerona', 'Figueras', 'Olot', 'Blanes', 'Lloret de Mar', 'Ripoll', 'Roses', 'Castelló d\'Empúries'],
            'Granada' => ['Granada', 'Almuñécar', 'Baza', 'Motril', 'Maracena', 'Huétor Vega', 'Churriana de la Vega', 'Atarfe'],
            'Guadalajara' => ['Guadalajara', 'Azuqueca de Henares', 'Marchamalo', 'Cabanillas del Campo', 'Alcalá del Henares', 'Pastrana', 'Mazarete'],
            'Guipúzcoa' => ['San Sebastián', 'Irún', 'Hernani', 'Tolosa', 'Eibar', 'Azpeitia', 'Arrasate', 'Zarautz'],
            'Huelva' => ['Huelva', 'Lepe', 'Almonte', 'Ayamonte', 'Palos de la Frontera', 'Moguer', 'Isla Cristina', 'Rociana del Condado'],
            'Huesca' => ['Huesca', 'Monzón', 'Barbastro', 'Fraga', 'Jaca', 'Binéfar', 'Sabiñánigo', 'Graus'],
            'Islas Baleares' => ['Palma de Mallorca', 'Ibiza', 'Mahón', 'Inca', 'Manacor', 'Marratxí', 'Calvià', 'Felanitx'],
            'Jaén' => ['Jaén', 'Linares', 'Andújar', 'Úbeda', 'Martos', 'Alcalá la Real', 'Bailén', 'Baeza'],
            'La Rioja' => ['Logroño', 'Calahorra', 'Arnedo', 'Alfaro', 'Nájera', 'Cervera del Río Alhama', 'Agoncillo', 'Autol'],
            'León' => ['León', 'Ponferrada', 'San Andrés del Rabanedo', 'Astorga', 'La Bañeza', 'Villaquilambre', 'Cistierna', 'Bembibre'],
            'Lérida' => ['Lérida', 'Tárrega', 'Balaguer', 'Cervera', 'Agramunt', 'Alcarràs', 'Mollerussa', 'Solsona'],
            'Lugo' => ['Lugo', 'Monforte de Lemos', 'Ribadeo', 'Vilalba', 'Sarria', 'Burela', 'Meira', 'Foz'],
            'Madrid' => ['Madrid', 'Alcalá de Henares', 'Móstoles', 'Fuenlabrada', 'Alcorcón', 'Leganés', 'Getafe', 'Torrejón de Ardoz'],
            'Málaga' => ['Málaga', 'Marbella', 'Ronda', 'Estepona', 'Fuengirola', 'Benalmádena', 'Mijas', 'Alhaurín de la Torre'],
            'Murcia' => ['Murcia', 'Cartagena', 'Lorca', 'Molina de Segura', 'Cieza', 'Mazarrón', 'Águilas', 'San Javier'],
            'Navarra' => ['Pamplona', 'Tudela', 'Estella', 'Burlada', 'Villava', 'Cizur', 'Ansoáin', 'Berrobi'],
            'Orense' => ['Orense', 'Verín', 'O Carballiño', 'Ribadavia', 'Allariz', 'Barbadás', 'O Barco de Valdeorras', 'Celanova'],
            'Palencia' => ['Palencia', 'Aguilar de Campoo', 'Villamuriel de Cerrato', 'Venta de Baños', 'Dueñas', 'Alar del Rey', 'Osorno la Mayor', 'Cervera de Pisuerga'],
            'Pontevedra' => ['Pontevedra', 'Vigo', 'Vilanova de Arousa', 'Marín', 'Vilagarcía de Arousa', 'Cangas', 'Poio', 'Sanxenxo'],
            'Salamanca' => ['Salamanca', 'Ciudad Rodrigo', 'Peñaranda de Bracamonte', 'Santa Marta de Tormes', 'Guijuelo', 'Vitigudino', 'Ledesma', 'La Alberca'],
            'Segovia' => ['Segovia', 'Cuéllar', 'Cantalejo', 'Carbonero el Mayor', 'San Ildefonso', 'La Lastrilla', 'San Cristóbal de Segovia', 'Ayllón'],
            'Sevilla' => ['Sevilla', 'Alcalá de Guadaíra', 'Dos Hermanas', 'Écija', 'Carmona', 'Utrera', 'Sanlúcar la Mayor', 'La Rinconada'],
            'Soria' => ['Soria', 'Agreda', 'San Esteban de Gormaz', 'Golmayo', 'Ólvega', 'Duruelo de la Sierra', 'San Esteban de Gormaz', 'Almazán'],
            'Tarragona' => ['Tarragona', 'Reus', 'Salou', 'Cambrils', 'Valls', 'Amposta', 'El Vendrell', 'Calafell'],
            'Teruel' => ['Teruel', 'Alcañiz', 'Andorra', 'Calamocha', 'Cella', 'Cascante del Río', 'Cella', 'El Pobo'],
            'Toledo' => ['Toledo', 'Talavera de la Reina', 'Illescas', 'Seseña', 'Ocaña', 'Sonseca', 'Polán', 'Almendral de la Cañada'],
            'Valencia' => ['Valencia', 'Gandía', 'Sagunto', 'Torrent', 'Alzira', 'Paterna', 'Xàtiva', 'Ontinyent'],
            'Valladolid' => ['Valladolid', 'Medina del Campo', 'Peñafiel', 'Laguna de Duero', 'Valladolid', 'Cigales', 'Olmedo', 'Aldeamayor de San Martín'],
            'Vizcaya' => ['Bilbao', 'Getxo', 'Barakaldo', 'Portugalete', 'Santurce', 'Erandio', 'Leioa', 'Basauri'],
            'Zamora' => ['Zamora', 'Benavente']
        ];


        foreach ($municipios as $nombreProvincia => $listaMunicipios) {
            $provincia = Provincia::where('nombre', $nombreProvincia)->first();

            if (!$provincia) {
                $provincia = Provincia::create(['nombre' => $nombreProvincia]);
            }

            foreach ($listaMunicipios as $nombreMunicipio) {
                Poblacion::create([
                    'nombre' => $nombreMunicipio,
                    'id_provincia' => $provincia->id,
                ]);
            }
        }
    }
}
